### ISSUE TITLE
Update config file format

### ISSUE THREAD

**Issue by Freyskeyd** [agglayer/agglayer#83]
## Description

*This PR can be mentored or part of a pairing session*

The config file format is currently using `toml` to express and define configuration.

This ticket is about finding the better solution to gather our configuration definition.
The goal is to not have something complex at first sight, but also something that we can use to express deep configuration definition.

`YAML` could have been an option to have more visual depth of the config, that *may* be something to explore.

### Ideas

- Define a max depth for the config (3 maybe, 4 max ?)
- Define if we want to support multiple format
- Define naming convention for keys (more after)

### Naming convention

Currently, the configuration is defining keys with both `PascalCase` and `lowercase`.

We have that:

```toml
[auth.gcpkms]
ProjectId = ""
Location = ""
Keyring = ""
KeyName = ""

[outbound.rpc.settle]
max_retries = 10
retry_interval = 1
confirmations = 3
```

I would suggest switching to either `snake_case` or `kebab-case`, I may find `kebab-case` more readable, but here's examples:

```toml
# snake_case

[auth.gcp_kms]
project_id = ""
location = ""
keyring = ""
key_name = ""

[outbound.rpc.settle]
max_retries = 10
retry_interval = 1
confirmations = 3
```

```toml
# kebab-case

[auth.gcp-kms]
project-id = ""
location = ""
keyring = ""
key-name = ""

[outbound.rpc.settle]
max-retries = 10
retry-interval = 1
confirmations = 3
```

## Acceptance

- [ ] Having a non-breaking configuration file (this ticket can be split into multiple ones)
- [ ] Having an agreement on the config format of the keys
- [ ] Having tests covering the non-breaking changes
- [ ] Update the `kurtosis-cdk` accordingly
